

sonar.projectKey=flask-app
sonar.sources=.
sonar.language=py
sonar.host.url=http://<sonarqube-ip>:9000
sonar.login=admin
sonar.password=admin

/*

sonar.host.url=http://localhost:9000
sonar.host.url=http://13.233.120.45:9000

| Property               | Meaning             |
| ---------------------- | ------------------- |
| `sonar.projectKey`     | Unique project name |
| `sonar.sources`        | Code location       |
| `sonar.language`       | Python project      |
| `sonar.host.url`       | SonarQube server    |
| `sonar.login/password` | Authentication      |

*/